### ISSUE TITLE
Multiple-effect action card schema

### ISSUE THREAD

**Issue by elliottomlinson** [elliottomlinson/rpcg#45]
Cards with multiple effects (i.e. proc-in-hand) should be bulleted for clarity

>- [ ] While holding this card in your hand, roll an additional d6 when you perform a melee attack. 
>- [ ] Cast to deal 6 damage to a visible target.

libvips will let us use UTF-8 symbols, we should consider those for unifying the presentation of effect types (i.e. cast vs in-hand).
Easy to understate how much this design chance would benefit our "brand identity" and the feel of the game IMO.

>⚡ Cast to deal 6 damage to a visible target.
>✋ While holding this card in your hand, roll an additional d6 when you perform a melee attack.

If we opt for symbols we can easily define them once (verbally, but ideally in writing once we have player-accessible rules) and organize the text further

>⚡ 6 damage to a visible target
>✋  Roll an additional d6 when you perform a melee attack

Design-wise we could build on the format with effect names:

>⚡ *Spell Spear:* 6 damage to a visible target
>✋  *Bound Bonus:* +1d6 melee damage

Or, drawing from the picture, provide better descriptions of how the effect works with the space instead. I much prefer the effect names though, I think they really suit the game.

>⚡ The sword flies from your hand, spearing a visible target and dealing 6 damage.
>✋  You wield the *Bound Sword*. Roll an additional d6 when you perform a melee attack.

_Originally posted by @elliottomlinson in https://github.com/elliottomlinson/rpcg/issues/40#issuecomment-830867014_

**Comment by elliottomlinson** [comment]
Opening an issue so we have a place to discuss this outside of a PR comment thread

**Comment by DuncanUszkay1** [comment]
>⚡ Spell Spear: 6 damage to a visible target

In this case, is spell spear the effect name for dealing 6 damage? Or does `Spell Spear` signify something else?

**Comment by DuncanUszkay1** [comment]
IMO we should introduce terms only when we feel something is fundamental to the game and is hard to explain in words. The best example of this is `Boost`. We've printed it on a few cards and I imagine we'll ensure that it's an effect that stays in the rotation. Describing what the effect does when a d20 hasn't been rolled is a little tricky.

If we want to quickly throw these at casual players and have them quickly come up with a plan to use them, we should minimize the friction of reading a card. Having to consult the rulebook is not ideal. With some effects like `Boost` it'll be seen so frequently that it should be fairly intuitive, and it has a clear relation to another card that is almost certainly in their hand.

These effect-in-hand cards aren't really ubiquitous enough to merit this yet, but I think they will be. I think we should hold off on canonizing them with a keyword until we see them played and learn whether or not it's going to be a card pattern that will see enough use to justify their complexity.

**Comment by elliottomlinson** [comment]
> > ⚡ Spell Spear: 6 damage to a visible target
> 
> In this case, is spell spear the effect name for dealing 6 damage? Or does `Spell Spear` signify something else?

Following the emergent *Action* has *effect(s)* nomenclature, the effect name. Without the context of the card, (in this case *Bound Sword*) and further without the context of other action cards, it's certainly confusing.

Perhaps more confusing that it's worth, but I think it'd be heavy-handed to declare it either way with certainty as it does serve to add some mechanical detail and a point of reference aside from *the passive effect of Bound Sword* while being concise and flavour-rich without demanding anything of the players.

**Comment by elliottomlinson** [comment]
With discretion, I think _fundamental to the game_ is grounds enough, as even the most casual player has had to learn the rules in the first place and a quick mention in that document/explanation would be sufficient. Especially for their visual definition over keywords, symbols for effect types serve to reduce friction in multiple ways.
- help the player keep track of their passive effects/available casts
- speed up play by letting the dm focus on the effect applied when cast
- simplify the process of comparing cards
- save the player skimming over "_with this card in your hand_" as they will begin to once familiar with the cards
- prevent the player from getting hung up on paraphrasing that doesn't match their expectations
- speed up the decision whether or not to use a new card immediately
- etc.

I don't necessarily believe that the distinction between _active_ and _passive_ (terms sufficient to describe the difference between *cast* and *in-hand* effects) is complex even for a casual player - I agree that using a rulebook is sub-optimal, I included the point about them as I was anticipating apprehension about making changes to the game in PR comments and "in our heads" as opposed to in writing.

**Comment by elliottomlinson** [comment]
Wanted to add that I agree this issue is low-priority until we see how players feel about/react to cards having passive effects, don't want to advocate for changing all of the formatting until we're sure this is a fun feature.

In weighing our decision we should also make a more deliberate point of considering passive effects as means to introduce cards that behave the way equipment does/defensive items do in other games i.e. providing a reduction to incoming damage (paired perhaps with a melee action like the Spike Shield from the last game) or immunity to some sort of damage (paired with a curse as you release the magic from the amulet).

**Comment by DuncanUszkay1** [comment]
>save the player skimming over "with this card in your hand" as they will begin to once familiar with the cards

In cases where this improves clarity, then I'd say it falls under the `Hard to express in words` category. `Hard to express clearly and concisely in words` is probably more apt. I agree that this example satisfies that condition.

>Following the emergent Action has effect(s) nomenclature, the effect name.

This is interesting, but I wonder if the Card name itself provides this piece of flavour in most cases. I suppose it depends on how often we'll have multiple-use cards. I'd probably have to see more examples.

>I agree that using a rulebook is sub-optimal, I included the point about them as I was anticipating apprehension about making changes to the game in PR comments and "in our heads" as opposed to in writing.

Agreed we should have a rulebook and should never keep rules in our head. I just think we should have very few rules and print them directly on the cards when it doesn't kludge them up.

**Comment by elliottomlinson** [comment]
For prosperity, the extremely professional first draft of the rules card

![cardmaster-rules-card-sketch](https://user-images.githubusercontent.com/8680290/127201431-cc4dbe0b-75cd-49c9-97ee-3b8032daf92f.png)

**Comment by elliottomlinson** [comment]
We've decided to go forward using the glyphs to denote the "cast" and "hand" effects and to take the place of their respective definitions (option 3 on the original post in this issue).

> **Male Parent's Errand-Inerrants**
> 
> ![image](https://user-images.githubusercontent.com/8680290/127204729-d7d27512-dd4d-4ddd-abdc-6fb8fc17a8d3.png)
> 
> ⚡ Repair a broken object or machine
> ✋ Women want you, fish fear you
> 
> *My wife said I should do lunges to stay in shape. 
That would be a big step forward.*
