### ISSUE TITLE
Remove all external references

### ISSUE THREAD

**Issue by DuncanUszkay1** [elliottomlinson/rpcg#47]
We've made a bunch of references to other games in the aciton cards. We want to cut those out.

The ones I'm aware of:
- Ender Pearl
- Doorstucker
- Proplauncher

_Originally posted by @DuncanUszkay1 in https://github.com/elliottomlinson/rpcg/pull/40#r624842393_

**Comment by DuncanUszkay1** [comment]
We have Skyrim screenshots in a bunch of our card art:
- Bound Bow
- Bound Sword
- Restore

We might want get rid of that, or process it more heavily to hide the reference

**Comment by elliottomlinson** [comment]
Compiled lists of references to other IPs (not counting stock images) for progress tracking:

**Card Illustrations**
- [ ] Animal Accomplice
- [ ] Axe Spin
- [ ] Bound Bow
- [ ] Bound Sword
- [ ] Caustic Companion
- [ ] Clippy
- [ ] Cowboy Reload
- [ ] Doorstucker
- [ ] Empouched Earth
- [ ] Ender Pearl
- [ ] Fireball
- [ ] Flaming Familiar
- [ ] Frostbite Familiar
- [ ] Grapple
- [ ] Gust of Wind
- [ ] Nullify Magic
- [ ] Proplauncher
- [ ] Shockwave Familiar
- [ ] Slag Familiar
- [ ] Stormcall

**Action Names**
- [ ] Bound Bow
- [ ] Bound Sword
- [ ] Clippy
- [ ] Doorstucker
- [ ] Ender Pearl
- [ ] Flaming Familiar
- [ ] Frostbite Familiar
- [ ] Mage Hand
- [ ] Monk Mode
- [ ] The Queen's Gambit
- [ ] Shockwave Familiar
- [ ] Slag Familiar
- [ ] Woody's Roundup

**Rules Text**
- [ ] Anvil Drop
- [ ] Empouched Earth
- [ ] The Swarm
- [ ] The Ultimatum
- [ ] Doorstucker
- [ ] Proplauncher
- [ ] The Ultimatum
- [ ] Smoke Bomb
- [ ] You're Toast
- [ ] Whip
- [ ] Flirt
- [ ] Arouse
- [ ] Seduce
- [ ] Master Mimic
- [ ] Tactical Reload
- [ ] Expert Reload
- [ ] Adlib
- [ ] Helter-Skelter
- [ ] Fork Lightning
- [ ] Elektra's Siphon
- [ ] Ignite
- [ ] Disguise
- [ ] Mirror Image

**Comment by DuncanUszkay1** [comment]
>Elektra's Siphon

Surprised to see this here, I just came up with that name randomly. Is it the image?

>Shockwave Familiar

What is this infringing on? I don't believe anyone owns the name familiar

**Comment by DuncanUszkay1** [comment]
This also raises some questions about what we want to ship as the "Cardmaster" product. I think that "Cardmaster" should come with a very basic default set of cards, with the intention that Players will want to add their own. 

I think we should distill that base set from what we have and ensure that has no external references. They should also be campaign agnostic. The Github repo you'd fork to start a campaign would just have the basic set and instructions on creating your own cards. 

We can keep an additional set of cards which are clearly marked as our own that wouldn't ship in the eventual product. That custom set doesn't need to abide by IP law, we'll just remove references if we find them corny.  Occasionally if an idea works out really well we can strip off the referential flavour and add it into the base set

**Comment by elliottomlinson** [comment]
> > Shockwave Familiar
> 
> What is this infringing on? I don't believe anyone owns the name familiar

My mistake, this one belongs in "Card Illustrations" rather than "Action Names", the name is fine but all the familiar set placeholder illustrations are re-coloured Skyrim screenshots.

**Comment by elliottomlinson** [comment]
>This also raises some questions about what we want to ship as the "Cardmaster" product. I think that "Cardmaster" should come with a very basic default set of cards, with the assumption that Players will want to add their own.

>I think we should distill that base set from what we have and ensure that has no external references. They should also be campaign agnostic. The Github repo you'd fork to start a campaign would just have the basic set and instructions on creating your own cards

Sounds good to me 👍🏻 

> We can keep an additional set of cards which are clearly marked as our own that wouldn't ship in the eventual product. That custom set doesn't need to abide by IP law, we'll just remove references if we find them corny. Occasionally if an idea works out really well we can strip off the referential flavour and add it into the base set

This will be the plan going forward. I didn't see this comment before making the changes in #53 - at least they'll make it easier to move cards to the base deck, no big deal.

**Comment by elliottomlinson** [comment]
resolved by #53
