### ISSUE TITLE
Rules text cleanup/schema

### ISSUE THREAD

**Issue by elliottomlinson** [elliottomlinson/rpcg#54]
Opening an issue as a place to discuss managing stylistic/semantic inconsistencies and other points regarding changes the rules text

_Originally posted by @elliottomlinson in https://github.com/elliottomlinson/rpcg/pull/53#discussion_r625182277_

**Comment by elliottomlinson** [comment]
Going through the catalogue I think we should make some changes (aside from those addressed in issue #47), mainly on the grounds of adding polish and clarity.

- [ ] remove or censor vulgar language
- [ ] unify the presentation of quotes in flavour text
- [ ] establish a simple convention for punctuation to resolve inconsistencies

**Comment by elliottomlinson** [comment]
At least until we decide on #45 I think the cards are all good at the moment, ready to mark this resolved pending review from @DuncanUszkay1

**Comment by DuncanUszkay1** [comment]
FYI you can put `closes [issue link]` and merging the PR will close the issue magically
