### ISSUE TITLE
Assets for E06

### ISSUE THREAD

**Issue by DuncanUszkay1** [elliottomlinson/rpcg#56]
In order of importance:

Figurines: (Just listing off all the details I can think of, I'm not too picky)
- [x] Rebel Soldiers. Holding guns. (IMO just 1 is fine, since they're rank soldiers in uniform so copy pasting them is appropriate)
- [x] General Huckleberry Finn. Wearing a military outfit. Holding a fishing rod
- [x] Queen Anastasya. Melancholic. Beautiful. Tall. Wearing an elaborate dress.
- [x] Gustav. Mushroom obsessed. Weirdo. Chef
- [x] Corporal Mary May. Elderly woman. Healer. Kind hearted.
- [x] Amateur chef (1). Chef outfit, holding a bunch of tupperware with food in it.
- [x] Amateur chef (1). Chef outfit, holding a hot pot of Mac and Cheese
- [x] Queen's Suitor (2 or 3). Slick. Douchey.
- [x] Mcdonalds employee (1). Bored. Apathetic
- [x] Knife Chef (A bunch). Wearing a typical chef outfit. Holding knives to throw
- [x] Chef's assistant (A bunch). Weapon is a rolling pin. Looks nervous/new.
- [x] Sumo Chef (2). Fat. Rushing melee combat. Maybe holding meat skewers
- [x] Expert Chef (2). Intelligent looking. Expert at hopping tables, using nearby tools

- [x] Chef's outfit for the Players

Assets:
- [x] Items you'd find in a kitchen. Especially anything dangerous
- [x] Different kinds of mushrooms. One will be used as the poisonous kind that Gustav plans to use for dinner
- [x] Plates
- [x] Silverware
- [x] Trash you'd find in a dumpster
- [x] Rotten Food

**Comment by elliottomlinson** [comment]
**Backgrounds**

- [ ] Mushroom Garden Room
- [ ] Main Kitchen
- [ ] Ingredients Room Pantry
- [ ] Classy Queueing Line
- [ ] Mall-style Mcdonalds
- [ ] Dining Room with Yellow Carpet
- [ ] Military Vehicle
- [ ] Big Fridge
- [ ] Vat of Oil
- [ ] Stacked Sandbags

**Comment by elliottomlinson** [comment]
As I've got lots of time this week I'll import a load of assets we can use for our next and future kitchens. Going to split the 'kitchen' items into decks so it's easier to manage for this session, here's the plan:

**Cutlery**

- [ ] Butcher Knife
- [ ] Bread Knife
- [ ] Paring Knife
- [ ] Steak Knife
- [ ] Carving Knife
- [ ] Cheese Knife
- [ ] Fillet Knife
- [ ] Dinner Fork
- [ ] Dessert Fork
- [ ] Cocktail Fork
- [ ] Spaghetti Fork
- [ ] Soup Spoon
- [ ] Teaspoon
- [ ] Tablespoon
- [ ] Salad Spoon
- [ ] Wooden Spoon
- [ ] Carving Fork
- [ ] Cleaver

**Utensils**

- [ ] Egg Whisk
- [ ] Soup Ladle
- [ ] Spatula
- [ ] Honing Rod
- [ ] Kitchen Shears
- [ ] Sieve
- [ ] Kitchen Tongs
- [ ] Garlic Press
- [ ] Grater
- [ ] Rolling Pin
- [ ] Can Opener
- [ ] Colander
- [ ] Saucepan
- [ ] Cast-Iron Pan
- [ ] Heavy Metal Pot
- [ ] Frying Pan
- [ ] Oven Mitts
- [ ] Meat Thermometer
- [ ] Plastic Container
- [ ] Bottle Opener
- [ ] Glass Bottle
- [ ] Glass Jar
- [ ] Mixing Bowl
- [ ] Kitchen Foil
- [ ] Tea Towel
- [ ] Metal Skewer
- [ ] Cutting Board

**Tableware**

- [ ] Entrée Plate
- [ ] Dinner Plate
- [ ] Appetizer Plate
- [ ] Salad Plate
- [ ] Dessert Plate
- [ ] Soup Bowl
- [ ] Cereal Bowl
- [ ] Bouillon Cup
- [ ] Wine Glass
- [ ] Champagne Glass
- [ ] Water Jug
- [ ] Bread Basket

** Small Appliances**

- [ ] Hand Blender
- [ ] Meat Grinder
- [ ] Crockpot
- [ ] Pressure Cooker
- [ ] Toaster
- [ ] Toaster Oven
- [ ] Panini Grill
- [ ] Power Mixer
- [ ] Fire Extinguisher
- [ ] Espresso Maker
- [ ] Juicer
- [ ] Blender
- [ ] Countertop Grill

** Pantry**

- [ ] Soup Can
- [ ] Flour
- [ ] Baking Powder
- [ ] Canned Tomatoes
- [ ] Canned Beans
- [ ] Peanut Butter
- [ ] White Rice
- [ ] Brown Rice
- [ ] Penne
- [ ] Rigatoni
- [ ] Fusilli
- [ ] Spaghetti
- [ ] Egg Noodles
- [ ] Rice Noodles
- [ ] Canned Salmon
- [ ] Spam
- [ ] Corned Beef
- [ ] Vinegar
- [ ] Apple Cider
- [ ] Olive Oil
- [ ] Lemon
- [ ] Apple
- [ ] Potato
- [ ] Onion
- [ ] Garlic
- [ ] Squash
- [ ] Shallots
- [ ] Oatmeal

**Fridge**

- [ ] Ketchup
- [ ] Mustard
- [ ] Maple Syrup
- [ ] Banana
- [ ] Cucumber
- [ ] Broccoli
- [ ] Celery
- [ ] Radish
- [ ] Spinach
- [ ] Green Beans
- [ ] Peas
- [ ] Lettuce
- [ ] Red Pepper
- [ ] Carrots
- [ ] Pineapple
- [ ] Turnip
- [ ] Leek
- [ ] Cherry
- [ ] Mango
- [ ] Strawberry
- [ ] Orange
- [ ] Avocado
- [ ] Peach
- [ ] Lime
- [ ] Blueberry
- [ ] Uncooked Red Meat
- [ ] Uncooked White Meat
- [ ] Beer
- [ ] Wine

**Cleaning**

- [ ] Abrasive Cleaner
- [ ] All-Surface Cleaner
- [ ] Sponge
- [ ] Dish Soap
- [ ] Scrubbing Brush
- [ ] Metal Scour
- [ ] Mop
- [ ] Mop Bucket
- [ ] Wet Floor Sign
- [ ] Rolling Wastebasket
- [ ] Paper Towel

**Comment by elliottomlinson** [comment]
As I've got lots of time this week I'll import a load of assets we can use for our next and future kitchens. Going to split the 'kitchen' items into decks so it's easier to manage for this session, here's the plan:

**Cutlery**

- [ ] Butcher Knife
- [ ] Bread Knife
- [ ] Paring Knife
- [ ] Steak Knife
- [ ] Carving Knife
- [ ] Cheese Knife
- [ ] Fillet Knife
- [ ] Dinner Fork
- [ ] Dessert Fork
- [ ] Cocktail Fork
- [ ] Spaghetti Fork
- [ ] Soup Spoon
- [ ] Teaspoon
- [ ] Tablespoon
- [ ] Salad Spoon
- [ ] Wooden Spoon
- [ ] Carving Fork
- [ ] Cleaver
- [ ] Silver Fork
- [ ] Silver Spoon
- [ ] Silver Knife

**Utensils**

- [ ] Egg Whisk
- [ ] Soup Ladle
- [ ] Spatula
- [ ] Honing Rod
- [ ] Kitchen Shears
- [ ] Sieve
- [ ] Kitchen Tongs
- [ ] Garlic Press
- [ ] Grater
- [ ] Rolling Pin
- [ ] Can Opener
- [ ] Colander
- [ ] Saucepan
- [ ] Cast-Iron Pan
- [ ] Heavy Metal Pot
- [ ] Frying Pan
- [ ] Oven Mitts
- [ ] Meat Thermometer
- [ ] Plastic Container
- [ ] Bottle Opener
- [ ] Glass Bottle
- [ ] Glass Jar
- [ ] Mixing Bowl
- [ ] Kitchen Foil
- [ ] Tea Towel
- [ ] Metal Skewer
- [ ] Cutting Board

**Tableware**

- [ ] Entrée Plate
- [ ] Dinner Plate
- [ ] Appetizer Plate
- [ ] Salad Plate
- [ ] Dessert Plate
- [ ] Soup Bowl
- [ ] Cereal Bowl
- [ ] Bouillon Cup
- [ ] Wine Glass
- [ ] Champagne Glass
- [ ] Water Jug
- [ ] Bread Basket

** Small Appliances**

- [ ] Hand Blender
- [ ] Meat Grinder
- [ ] Crockpot
- [ ] Pressure Cooker
- [ ] Toaster
- [ ] Toaster Oven
- [ ] Panini Grill
- [ ] Power Mixer
- [ ] Fire Extinguisher
- [ ] Espresso Maker
- [ ] Juicer
- [ ] Blender
- [ ] Countertop Grill

** Pantry**

- [ ] Soup Can
- [ ] Flour
- [ ] Baking Powder
- [ ] Canned Tomatoes
- [ ] Canned Beans
- [ ] Peanut Butter
- [ ] White Rice
- [ ] Brown Rice
- [ ] Penne
- [ ] Rigatoni
- [ ] Fusilli
- [ ] Spaghetti
- [ ] Egg Noodles
- [ ] Rice Noodles
- [ ] Canned Salmon
- [ ] Spam
- [ ] Corned Beef
- [ ] Vinegar
- [ ] Apple Cider
- [ ] Olive Oil
- [ ] Lemon
- [ ] Apple
- [ ] Potato
- [ ] Onion
- [ ] Garlic
- [ ] Squash
- [ ] Shallots
- [ ] Oatmeal

**Fridge**

- [ ] Ketchup
- [ ] Mustard
- [ ] Maple Syrup
- [ ] Banana
- [ ] Cucumber
- [ ] Broccoli
- [ ] Celery
- [ ] Radish
- [ ] Spinach
- [ ] Green Beans
- [ ] Peas
- [ ] Lettuce
- [ ] Red Pepper
- [ ] Carrots
- [ ] Pineapple
- [ ] Turnip
- [ ] Leek
- [ ] Cherry
- [ ] Mango
- [ ] Strawberry
- [ ] Orange
- [ ] Avocado
- [ ] Peach
- [ ] Lime
- [ ] Blueberry
- [ ] Uncooked Red Meat
- [ ] Uncooked White Meat
- [ ] Red Sauce
- [ ] Brown Sauce
- [ ] Beer
- [ ] Wine

**Cleaning**

- [ ] Abrasive Cleaner
- [ ] All-Surface Cleaner
- [ ] Bleach
- [ ] Ammonia
- [ ] Metal Bucket
- [ ] Rubber Gloves
- [ ] Sponge
- [ ] Dish Soap
- [ ] Scrubbing Brush
- [ ] Metal Scour
- [ ] Mop
- [ ] Mop Bucket
- [ ] Wet Floor Sign
- [ ] Rolling Wastebasket
- [ ] Paper Towel

**Comment by elliottomlinson** [comment]
As I've got lots of time this week I'll import a load of assets we can use for our next and future kitchens. Going to split the 'kitchen' items into decks so it's easier to manage for this session, here's the plan:

**Cutlery**

- [ ] Butcher Knife
- [ ] Bread Knife
- [ ] Paring Knife
- [ ] Steak Knife
- [ ] Carving Knife
- [ ] Cheese Knife
- [ ] Fillet Knife
- [ ] Dinner Fork
- [ ] Dessert Fork
- [ ] Cocktail Fork
- [ ] Spaghetti Fork
- [ ] Soup Spoon
- [ ] Teaspoon
- [ ] Tablespoon
- [ ] Salad Spoon
- [ ] Wooden Spoon
- [ ] Carving Fork
- [ ] Cleaver
- [ ] Silver Fork
- [ ] Silver Spoon
- [ ] Silver Knife

**Utensils**

- [ ] Egg Whisk
- [ ] Soup Ladle
- [ ] Spatula
- [ ] Honing Rod
- [ ] Kitchen Shears
- [ ] Sieve
- [ ] Kitchen Tongs
- [ ] Garlic Press
- [ ] Grater
- [ ] Rolling Pin
- [ ] Can Opener
- [ ] Colander
- [ ] Saucepan
- [ ] Cast-Iron Pan
- [ ] Heavy Metal Pot
- [ ] Frying Pan
- [ ] Oven Mitts
- [ ] Meat Thermometer
- [ ] Plastic Container
- [ ] Bottle Opener
- [ ] Glass Bottle
- [ ] Glass Jar
- [ ] Mixing Bowl
- [ ] Kitchen Foil
- [ ] Tea Towel
- [ ] Metal Skewer
- [ ] Cutting Board

**Tableware**

- [ ] Entrée Plate
- [ ] Dinner Plate
- [ ] Appetizer Plate
- [ ] Salad Plate
- [ ] Dessert Plate
- [ ] Soup Bowl
- [ ] Cereal Bowl
- [ ] Bouillon Cup
- [ ] Wine Glass
- [ ] Champagne Glass
- [ ] Water Jug
- [ ] Bread Basket

**Small Appliances**

- [ ] Hand Blender
- [ ] Meat Grinder
- [ ] Crockpot
- [ ] Pressure Cooker
- [ ] Toaster
- [ ] Toaster Oven
- [ ] Panini Grill
- [ ] Power Mixer
- [ ] Fire Extinguisher
- [ ] Espresso Maker
- [ ] Juicer
- [ ] Blender
- [ ] Countertop Grill

**Pantry**

- [ ] Soup Can
- [ ] Flour
- [ ] Baking Powder
- [ ] Canned Tomatoes
- [ ] Canned Beans
- [ ] Peanut Butter
- [ ] White Rice
- [ ] Brown Rice
- [ ] Penne
- [ ] Rigatoni
- [ ] Fusilli
- [ ] Spaghetti
- [ ] Egg Noodles
- [ ] Rice Noodles
- [ ] Canned Salmon
- [ ] Spam
- [ ] Corned Beef
- [ ] Vinegar
- [ ] Apple Cider
- [ ] Olive Oil
- [ ] Lemon
- [ ] Apple
- [ ] Potato
- [ ] Onion
- [ ] Garlic
- [ ] Squash
- [ ] Shallots
- [ ] Oatmeal

**Fridge**

- [ ] Ketchup
- [ ] Mustard
- [ ] Maple Syrup
- [ ] Banana
- [ ] Cucumber
- [ ] Broccoli
- [ ] Celery
- [ ] Radish
- [ ] Spinach
- [ ] Green Beans
- [ ] Peas
- [ ] Lettuce
- [ ] Red Pepper
- [ ] Carrots
- [ ] Pineapple
- [ ] Turnip
- [ ] Leek
- [ ] Cherry
- [ ] Mango
- [ ] Strawberry
- [ ] Orange
- [ ] Avocado
- [ ] Peach
- [ ] Lime
- [ ] Blueberry
- [ ] Uncooked Red Meat
- [ ] Uncooked White Meat
- [ ] Red Sauce
- [ ] Brown Sauce
- [ ] Beer
- [ ] Wine

**Cleaning**

- [ ] Abrasive Cleaner
- [ ] All-Surface Cleaner
- [ ] Bleach
- [ ] Ammonia
- [ ] Metal Bucket
- [ ] Rubber Gloves
- [ ] Sponge
- [ ] Dish Soap
- [ ] Scrubbing Brush
- [ ] Metal Scour
- [ ] Mop
- [ ] Mop Bucket
- [ ] Wet Floor Sign
- [ ] Rolling Wastebasket
- [ ] Paper Towel

**Comment by elliottomlinson** [comment]
**Mushrooms**

- [x] Button
- [x] Cremini
- [x] Portobello
- [x] Oyster
- [x] King Oyster
- [x] Chanterelle
- [x] Porcini
- [x] Hedgehog
- [x] Chicken of the Woods
- [x] Wood Blewit
- [x] Morel
- [x] Enoki
- [x] Shimeji
- [x] Shiitake
- [x] Maitake
- [x] Reishi
- [x] Lion's Mane
- [x] Giant Puffball
- [x] Common Ink-Cap
- [x] Field
- [x] Gypsy
- [x] Parasol
- [x] Super Mario
- [x] Mario Kart
- [x] Psilocybin
- [x] Death Cap
- [x] False Morel
- [x] Fly Agaric
- [x] Autumn Skullcap

**Comment by elliottomlinson** [comment]
Resolved by #58
