### ISSUE TITLE
Glyphs

### ISSUE THREAD

**Issue by elliottomlinson** [elliottomlinson/rpcg#80]
@DuncanUszkay1 Here are the ideas I've had so far, let me know what you think. I've put the symbol I prefer in front. 

Glyph | Meaning
-- | --
⚡ | Active
✋ | Passive
🦶💨♟️ | Shift
🤜👉🧲➡️⏩ | Push, Pull
👍🔼⬆️ | Boost
👎🔽⬇️ | Fluster

**Comment by elliottomlinson** [comment]
I think we should drop the terms *Active* and *Passive* and canonize *Cast* and *Hand* in their place.

It may make the rules card easier, since it works better for both actions and items.
Also since the main distinction between ⚡ and ✋ is whether or not the card is *cast* from your *hand* on use, I think it'd be better for inexperienced players.

**Comment by elliottomlinson** [comment]
I think we should merge *Push* and *Pull* into *Force* as well, since they have such a similar effect.

**Comment by elliottomlinson** [comment]
Following our resolution to merge the *Push* and *Pull* cards into *Force* and pre-emptively formalizing #81, the updated glyph table is now as follows:

Glyph | Meaning
-- | --
⚡ | Cast
✋ | Hand
🦶💨♟️ | Shift
🤜👉🧲➡️⏩ | Force
👍🔼⬆️ | Boost
👎🔽⬇️ | Fluster

**Comment by elliottomlinson** [comment]
for reference this is what it looks like with the windows default emoji
![image](https://user-images.githubusercontent.com/8680290/127250536-079d19f9-00a4-4cc4-845b-50a00f9f6196.png)

**Comment by elliottomlinson** [comment]
Here's how they look in windows btw
![image](https://user-images.githubusercontent.com/8680290/127250647-32774f46-8975-4e98-ac85-e1807950d404.png)

**Comment by DuncanUszkay1** [comment]
I wonder how they'll be rendered by IMGKit 🤔  Hopefully it's not OS dependent

**Comment by elliottomlinson** [comment]
> I wonder how they'll be rendered by IMGKit 🤔 Hopefully it's not OS dependent

Been wondering this as well, I imagine the thought's occurred to you but might be worth having png versions in an asset folder to be safe.

**Comment by elliottomlinson** [comment]
Moved to #94
